### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Rogenar** [Craftjakob/More-Crossbows-CJ#1]
[latest.log](https://github.com/Craftjakob/More-Crossbows-CJ/files/14427482/latest.log)

**Comment by Mysticpasta1** [comment]
[05:52:33] [main/WARN] [mixin/]: @Redirect conflict. Skipping morebows-common.mixins.json:client.FovMixin from mod morebows->@Redirect::getFieldOfViewModifier(Lnet/minecraft/world/item/ItemStack;Lnet/minecraft/world/item/Item;)Z with priority 1000, already redirected by morecrossbows-common.mixins.json:client.FovMixin from mod morecrossbows->@Redirect::getFieldOfViewModifier(Lnet/minecraft/world/item/ItemStack;Lnet/minecraft/world/item/Item;)Z with priority 1000

**Comment by Craftjakob** [comment]
That is interesting, because it crashes only, if you have More Bows installed.
Because of this Mixin, that fix the Fov Animation from Bow and Crossbow.
```
@Mixin(AbstractClientPlayer.class)
public class FovMixin {
    @Redirect(method = "getFieldOfViewModifier", at = @At(value = "INVOKE", target = "Lnet/minecraft/world/item/ItemStack;is(Lnet/minecraft/world/item/Item;)Z"))
    private boolean getFieldOfViewModifier(ItemStack stack, Item item) {
        return stack.getItem() instanceof CrossbowItem;
    }
}
```

**Comment by Mysticpasta1** [comment]
yes can it be fixed

**Comment by Craftjakob** [comment]
Yes sure, I can also remove that, and it fixed, but then the fov does not update.

**Comment by Mysticpasta1** [comment]
can you try making both an inject mixin

**Comment by Craftjakob** [comment]
Yes

**Comment by Craftjakob** [comment]
Wow, now I have destroyed the normal bows and crossbows fov.

**Comment by Mysticpasta1** [comment]
XD

**Comment by Craftjakob** [comment]
Wow I see, that you don't need the fov update for the Crossbow, so I can remove it, but I found another bug, the Crossbow is invisible, if you try to load it on fabric, but only in first Person. That does not happen in forge.

**Comment by Mysticpasta1** [comment]
ah

**Comment by Mysticpasta1** [comment]
can you upload the new version for the crossbows, for forge :D

**Comment by Mysticpasta1** [comment]
can you upload the new version for the crossbows, for forge :D

**Comment by Craftjakob** [comment]
I gonna also upload it for Fabric, because I think that this is a fabric related problem.

**Comment by Mysticpasta1** [comment]
sure :D

**Comment by Craftjakob** [comment]
I uploaded it, but now you have to wait a few seconds, because CurseForge is now checking the file.
